language: ruby
sudo: false
cache: bundler
services:
  - redis-server
rvm:
  - 2.1
  - 2.2.4
  - 2.2-head
  - ruby-head
  - jruby
  - jruby-head
  - rbx-2.2
  - rbx-2.3
  - rbx-2.4
  - rbx
  - rbx-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-head
    - rvm: jruby-head
