dist: bionic
language: ruby
sudo: false
cache: bundler
services:
  - redis-server
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - jruby-9.1.17.0
  - jruby-9.2.5.0
env:
  - "sidekiq=3.5.4"
  - "sidekiq=4.2.10"
  - "sidekiq=5.1.3"
  - "sidekiq=5.2.5"
  - "sidekiq=master"
matrix:
  allow_failures:
    - env: "sidekiq=master"
  exclude:
    # sidekiq 5 does not support < ruby 2.2.2
    - rvm: 2.0.0
      env: sidekiq=master
    - rvm: 2.0.0
      env: sidekiq=5.1.3
    - rvm: 2.0.0
      env: sidekiq=5.2.5
    - rvm: 2.1.10
      env: sidekiq=master
    - rvm: 2.1.10
      env: sidekiq=5.1.3
    - rvm: 2.1.10
      env: sidekiq=5.2.5
  fast_finish: true
after_success:
  - bundle exec codeclimate-test-reporter
