language: ruby
sudo: false
cache: bundler
services:
  - redis-server
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - ruby-head
  - jruby-9.0.4.0
  - jruby-head
  - rbx-2.6
  - rbx-2.7
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
addons:
  code_climate:
    repo_token: dee2fdcb3562533038a22e862c0fc91a6f1fa38730cd2b77177655e5b9507c83
