dist: bionic
language: ruby
sudo: false
cache: bundler
services:
  - redis-server
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - jruby-9.1.17.0
  - jruby-9.2.8.0
env:
  - "sidekiq=3.5.4"
  - "sidekiq=4.2.10"
  - "sidekiq=5.1.3"
  - "sidekiq=5.2.7"
  - "sidekiq=6.0.1"
  - "sidekiq=master"
matrix:
  allow_failures:
    - env: "sidekiq=master"
  fast_finish: true
after_success:
  - bundle exec codeclimate-test-reporter
